export enum ActionType {
  // PRODUCTS RESOURCE
  APPEND_PRODUCTS,
  REFRESH_PRODUCTS,
  UPDATE_PRODUCT,
  REMOVE_PRODUCTS,

  // EMPLOYEES RESOURCE
  APPEND_EMPLOYEES,
  REFRESH_EMPLOYEES,
  UPDATE_EMPLOYEE,
  REMOVE_EMPLOYEES,

  // MODALS
  ADD_MODAL,
  REMOVE_MODAL,

  // ORDER_ENTRY RESOURCE
  APPEND_ORDER_ENTRY,
  REFRESH_ORDER_ENTRY,
  UPDATE_ORDER_ENTRY,
  REMOVE_ORDER_ENTRY,

  // BILLS
  APPEND_BILLS,
  REFRESH_BILLS,
  UPDATE_BILLS,
  REMOVE_BILLS,

  // RESERVATIONS
  APPEND_RESERVATIONS,
  REFRESH_RESERVATIONS,
  UPDATE_RESERVATIONS,
  REMOVE_RESERVATIONS,
}