export enum ActionType {
  // PRODUCTS RESOURCE
  APPEND_PRODUCTS,
  REFRESH_PRODUCTS,
  UPDATE_PRODUCT,
  REMOVE_PRODUCTS,

  // EMPLOYEES RESOURCE
  APPEND_EMPLOYEES,
  REFRESH_EMPLOYEES,
  UPDATE_EMPLOYEE,
  REMOVE_EMPLOYEES,

  // MODALS
  ADD_MODAL,
  REMOVE_MODAL,
}