name: backend

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
        working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Setup dredd
        run: npm install -g dredd
      - name: Build
        run: dotnet build --configuration Release
        working-directory: ${{env.working-directory}}
      - name: Test backend
        run: dotnet test
        working-directory: ${{env.working-directory}}
      - name: Run backend
        run: dotnet run
        working-directory: ${{env.working-directory}}
      - name: Test integration
        run: dredd ./reference/resourceReservationSystem.v1.yaml 127.0.0.1:5000
