name: frontend

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Build
        run: dotnet build --configuration Release
        working-directory: ${{env.working-directory}}
      - name: Test
        run: dotnet test
        working-directory: ${{env.working-directory}}

